artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-b6fd695c7b61436d98d27ad0f5dbcfa2/artifacts
creation_timestamp: 1756617719984
experiment_id: '0'
last_updated_timestamp: 1756617728772
model_id: m-b6fd695c7b61436d98d27ad0f5dbcfa2
model_type: null
name: model
source_run_id: fee51f89cb2a4b0dabeea038e21c6cf4
status: 2
status_message: null
