artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/d9448b6d316141b2be78d661218f9e5c/artifacts
end_time: 1756745777919
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d9448b6d316141b2be78d661218f9e5c
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1756745751695
status: 3
tags: []
user_id: Hazra
