artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/bf08405da9ef46ebbf1500d7cb06caed/artifacts
end_time: 1756621935357
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bf08405da9ef46ebbf1500d7cb06caed
run_name: GradientBoostingClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756621926798
status: 3
tags: []
user_id: Hazra
