artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/ed0e5a34984b41c5b70b350b44a63d2f/artifacts
end_time: 1756626765720
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ed0e5a34984b41c5b70b350b44a63d2f
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1756626748583
status: 3
tags: []
user_id: Hazra
