artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/fb8b155f49494c6f91e9635d98a1216f/artifacts
end_time: 1756621720461
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: fb8b155f49494c6f91e9635d98a1216f
run_name: RandomForestClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756621708452
status: 3
tags: []
user_id: Hazra
