artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/91cfd10411ee4da1bbca46e51c60b793/artifacts
end_time: 1756745704777
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 91cfd10411ee4da1bbca46e51c60b793
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1756745668729
status: 3
tags: []
user_id: Hazra
