artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-5cf6fec3fb864541a60b18695e9f68ec/artifacts
creation_timestamp: 1756617692521
experiment_id: '0'
last_updated_timestamp: 1756617698829
model_id: m-5cf6fec3fb864541a60b18695e9f68ec
model_type: null
name: model
source_run_id: 73bc5438950d4ab89672ffee7da42660
status: 2
status_message: null
