artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/340bb1ede8f64dfcb39a4f8cdb55b74c/artifacts
end_time: 1756621914918
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 340bb1ede8f64dfcb39a4f8cdb55b74c
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1756621896583
status: 3
tags: []
user_id: Hazra
