artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-dc3151307033417dbda395d7a998a77e/artifacts
creation_timestamp: 1756621920000
experiment_id: '0'
last_updated_timestamp: 1756621926746
model_id: m-dc3151307033417dbda395d7a998a77e
model_type: null
name: model
source_run_id: d8abfc981211482a91d6bd24d38728b3
status: 2
status_message: null
