artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-4da3cf1efa6e4988a54b9b1d0fd99f0e/artifacts
creation_timestamp: 1756621905964
experiment_id: '0'
last_updated_timestamp: 1756621914900
model_id: m-4da3cf1efa6e4988a54b9b1d0fd99f0e
model_type: null
name: model
source_run_id: 340bb1ede8f64dfcb39a4f8cdb55b74c
status: 2
status_message: null
