artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0
creation_time: 1756617557908
experiment_id: '0'
last_update_time: 1756617557908
lifecycle_stage: active
name: Default
