artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/4d5566ea59bb4cb7a79f55cb38813148/artifacts
end_time: 1756617679329
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4d5566ea59bb4cb7a79f55cb38813148
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1756617663128
status: 3
tags: []
user_id: Hazra
