artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/78d8be0680194ab2adb6a776d71fce8f/artifacts
end_time: 1756626777522
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 78d8be0680194ab2adb6a776d71fce8f
run_name: RandomForestClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756626765763
status: 3
tags: []
user_id: Hazra
