artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-928ae76a193c48caab0f645ae57de60c/artifacts
creation_timestamp: 1756617684149
experiment_id: '0'
last_updated_timestamp: 1756617690489
model_id: m-928ae76a193c48caab0f645ae57de60c
model_type: null
name: model
source_run_id: 24d26510dea14844850b650dfa73ae55
status: 2
status_message: null
