artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/55459672375c4381b5a430c644344e85/artifacts
end_time: 1756626786107
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 55459672375c4381b5a430c644344e85
run_name: GradientBoostingClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756626777568
status: 3
tags: []
user_id: Hazra
