artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/e5220835d1574c9aa14cecbca4b3294f/artifacts
end_time: 1756622487884
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e5220835d1574c9aa14cecbca4b3294f
run_name: GradientBoostingClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756622479050
status: 3
tags: []
user_id: Hazra
