artifact_location: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/models/m-5c43b343a3bf4900b2be6442a0b14e6b/artifacts
creation_timestamp: 1756745682960
experiment_id: '0'
last_updated_timestamp: 1756745704753
model_id: m-5c43b343a3bf4900b2be6442a0b14e6b
model_type: null
name: model
source_run_id: 91cfd10411ee4da1bbca46e51c60b793
status: 2
status_message: null
