artifact_uri: file:///C:/gitrepo/GitHub/loan_eligible_ml_app/src/resources/ml_loan_runs/0/ec2e3707ceb649a98a3425ca861e4cb5/artifacts
end_time: 1756621976014
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ec2e3707ceb649a98a3425ca861e4cb5
run_name: RandomForestClassifier
source_name: ''
source_type: 4
source_version: ''
start_time: 1756621964832
status: 3
tags: []
user_id: Hazra
